### ISSUE TITLE
Thoughta

### ISSUE THREAD

**Issue by mikebutts** [mohaldev/music#1]
https://github.com/mohaldev/music/blob/87bfa84d78d5e5cf087e0f4d9081bf898b8f0e20/src/util/Spotify.js#L46-L54

Becareful with one liners, 
```
if(condition) {
   return
}.
```
Also, when setting a variable you can just say
```
  let bob;
```

this will set a variable with no value. Just food for thought.

**Comment by mohaldev** [comment]
Hi Michael,

Thanks for the review. Good points on both. Especially about the second point about setting the variable.
